fake_licence = {
  "version": "1.0",
  "response": [
    {
      "hostId": "CAMPUS-Access1",
      "isEulaAccepted": True,
      "status": "INUSE",
      "licenseIndex": 1,
      "id": "aa6c47a1-5b37-40fe-954c-803ae554a33c",
      "maxUsageCount": 10,
      "eulaStatus": True,
      "name": "Ipservices",
      "isEulaApplicable": True,
      "type": "PERMANENTRIGHTTOUSE",
      "description": "Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "status": "INACTIVE",
      "validityPeriodRemaining": 7776000,
      "licenseIndex": 2,
      "id": "2271e82a-b50a-4ab4-b8ce-31f1de64332b",
      "maxUsageCount": 10,
      "name": "Ipservices eval",
      "type": "EVALRIGHTTOUSE",
      "description": "Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "validityPeriod": 7776000,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "name": "Ipbase",
      "status": "INACTIVE",
      "type": "PERMANENTRIGHTTOUSE",
      "description": "Licensing Info",
      "licenseIndex": 3,
      "id": "e608c188-97ec-4854-9b80-7b96ad40d2c4",
      "storeName": "",
      "storedUsed": 1,
      "maxUsageCount": 10,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "status": "INACTIVE",
      "validityPeriodRemaining": 7776000,
      "licenseIndex": 4,
      "id": "a7b15e2c-4229-4f05-bed3-44a7e76af6b5",
      "maxUsageCount": 10,
      "name": "Ipbase eval",
      "type": "EVALRIGHTTOUSE",
      "description": "Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "validityPeriod": 7776000,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "isEulaAccepted": True,
      "status": "INACTIVE",
      "licenseIndex": 5,
      "id": "3a6b3265-0495-4485-ba9a-2e7b029574bf",
      "maxUsageCount": 10,
      "eulaStatus": True,
      "name": "Lanbase",
      "isEulaApplicable": True,
      "type": "PERMANENTRIGHTTOUSE",
      "description": "Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "counted": True,
      "status": "INACTIVE",
      "validityPeriodRemaining": 6825600,
      "isCounted": True,
      "licenseIndex": 6,
      "id": "4921f3de-b787-41b8-b199-7ced4ea92ba6",
      "name": "Apcount eval",
      "type": "EVALRIGHTTOUSE",
      "description": "Ap Count Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "validityPeriod": 7776000,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "counted": True,
      "status": "INACTIVE",
      "isCounted": True,
      "licenseIndex": 7,
      "id": "7e5a138e-31a1-4667-9997-445972455f45",
      "maxUsageCount": 10,
      "name": "Base apcount",
      "type": "PERMANENTRIGHTTOUSE",
      "description": "Ap Count Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "featureVersion": "1.0"
    },
    {
      "hostId": "CAMPUS-Access1",
      "counted": True,
      "isEulaAccepted": True,
      "status": "INUSE",
      "isCounted": True,
      "licenseIndex": 8,
      "id": "b9aaf7a2-f6f8-412d-ab63-9187e1c83af7",
      "maxUsageCount": 10,
      "eulaStatus": True,
      "name": "Adder apcount",
      "isEulaApplicable": True,
      "type": "PERMANENTRIGHTTOUSE",
      "description": "Ap Count Licensing Info",
      "storeName": "",
      "storedUsed": 1,
      "featureVersion": "1.0"
    }
  ]
}
